create or replace TABLE ORDERS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	ORDER_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	AMOUNT NUMBER(12,2) NOT NULL,
	STATUS VARCHAR(20)
);
