name: "Copy DEV Schemas to PROD (CSV)"

on:
  push:
    branches: [ "main", "demo" ]
    paths:
      - "tables.csv"          # run when you change the CSV
      - ".github/workflows/copy-schemas.yml"
  workflow_dispatch:          # allow manual runs too

jobs:
  copy:
    runs-on: ubuntu-latest
    env:
      # Snowflake connection (store these as repo → Settings → Secrets → Actions)
      SNOWFLAKE_USER: SAATVIKRAYALU
      SNOWFLAKE_PASSWORD: w_vrX7.CVfFNh.8
      SNOWFLAKE_ACCOUNT:  JFUVMRO-FB11082
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      # Optional: SNOWFLAKE_ROLE: CICD_PROD_ROLE

      # Source/Target (change defaults here or set as repo variables)
      DEV_DB: DEV_DB
      DEV_SCHEMA: PUBLIC
      PROD_DB: PROD_DB
      PROD_SCHEMA: PUBLIC

      # CSV path
      TABLES_FILE: tables.csv

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Snowflake connector
        run: |
          python -m pip install --upgrade pip
          pip install --quiet snowflake-connector-python

      - name: Copy schemas
        run: |
          python copy_schemas.py

