name: "Copy DEV Schemas to PROD (CSV)"

on:
  push:
    branches: [ "main", "demo" ]
    paths:
      - "tables.csv"
      - ".github/workflows/copy-schemas.yml"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_USER:     SAATVIKRAYALU
      SNOWFLAKE_PASSWORD: w_vrX7.CVfFNh.8
      SNOWFLAKE_ACCOUNT:  JFUVMRO-FB11082
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      DEV_DB: DEV_DB
      DEV_SCHEMA: PUBLIC
      PROD_DB: PROD_DB
      PROD_SCHEMA: PUBLIC
      TABLES_FILE: tables.csv

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # ✅ NEW: make sure our workspace is up-to-date BEFORE generating files
      - name: Sync branch
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          git fetch origin "${BRANCH}"
          # autostash handles any incidental changes from previous steps
          git pull --rebase --autostash origin "${BRANCH}" || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Snowflake connector
        run: |
          python -m pip install --upgrade pip
          pip install --quiet snowflake-connector-python

      - name: Copy schemas (creates schema_snapshots and tables in PROD)
        run: python copy_schemas.py

      - name: List snapshot files
        run: |
          echo "Branch: ${GITHUB_REF_NAME}"
          find schema_snapshots -maxdepth 3 -type f | sort || true

      # ✅ Simplified: just commit & push (no pull here)
      - name: Commit & push snapshot
        run: |
          git config user.name  "schema-bot"
          git config user.email "schema-bot@users.noreply.github.com"

          # ensure empty dirs are tracked if any
          find schema_snapshots -type d -empty -exec touch {}/.gitkeep \; || true

          git add -A schema_snapshots/
          if git diff --staged --quiet; then
            echo "No snapshot changes to commit."
            exit 0
          fi

          BRANCH="${GITHUB_REF_NAME}"
          git commit -m "chore(schema): add schema snapshots"
          git push origin "HEAD:${BRANCH}"

      # optional: save snapshots even if push blocked by branch protection
      - name: Upload snapshot artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: schema-snapshot-${{ github.run_id }}
          path: schema_snapshots/
